name: Auto-generate scripts

on:
  push:
    branches: [ main ]
    paths:
      - "generate/**"
      - ".github/workflows/**"

  schedule:
  - cron: "0 9 * * *"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: ^1.17

    - name: "Run generator tests"
      shell: bash
      run: |
        sudo bash ./test.sh 2>&1
      working-directory: generate

    - name: "Run regeneration script"
      shell: bash
      run: |
        sudo bash ./generate-all.sh 2>&1
      working-directory: generate


   - name: Add & Commit
     uses: EndBug/add-and-commit@v9.1.1
     with:
       author_name: GitHub Actions
       author_email: 41898282+github-actions[bot]@users.noreply.github.com
       message: update userscripts
       add: *.user.js
 


        
name: Auto-generate scripts

on:

  push:

    branches: [ main ]

    paths:

      - "generate/**"

      - ".github/workflows/**"

  schedule:

  - cron: "* 9 * * *"

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3.2.0

    - name: Set up Go

      uses: actions/setup-go@v3.5.0

      with:

        go-version: ^1.17

    - name: "Run generator tests"

      shell: bash

      run: |

        sudo bash ./test.sh 2>&1

      working-directory: generate

    - name: "Run regeneration script"

      shell: bash

      run: |

        sudo bash ./generate-all.sh 2>&1

      working-directory: generate

    - name: Generate tag name

      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV

    - name: Release scripts

      uses: softprops/action-gh-release@v1

      with:

        files: block/*.user.js

        name: Automatic script generation

        tag_name: ${{ env.TAG_NAME }}

        body: "This release contains all scripts provided by this repository.\n\nPlease see [the main project page](${{ github.server_url }}/${{ github.repository }}) for a description of the scripts."

        body_path: generate/release/release.md

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  

    - name: Commit userscript

      uses: EndBug/add-and-commit@v9.1.1

      with:

        add: '*.user.js'

        default_author: github_actions

        message: 'commit at ${{ env.TAG_NAME }}'

        push: true

  

    - name: Delete older releases

      uses: dev-drprasad/delete-older-releases@v0.2.1

      with:

        keep_latest: 0

        delete_tags: true

      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
